---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---


```{r setup}
knitr::opts_chunk$set(
  warning = FALSE, # ocultamos warnings para un reporte final más limpio
  message = FALSE, # ocultamos mensajes (ej. carga de librerías)
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

```



```{r prepare_codebook}
library(codebook)
library(arrow)
library(here)

# Cargamos nuestra base de datos documentada, generada en el script 07_Documentar.R
codebook_data <- read_parquet(here("datos", "procesados", "base_codebook_110726.parquet"))

# Omitimos detect_missing() y detect_scales(): nuestros valores perdidos ya
# fueron tratados en el script 02_Acondicionar.R, y nuestras variables no
# siguen el patrón de nombres de escalas (scale_1, scale_2R, ...) que
# detect_scales() necesita para reconocer agregados.
```


creacion codebook

```{r codebook}
# omit metadata_json (uses HTML) to avoid an error when knitting to PDF;
# metadata_table and other components are automatically
# rendered as static tables for PDF output
codebook(codebook_data)
```
